CREATE TABLE IF NOT EXITST users
(
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  pass_hash BLOB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email ON users (email);

CREATE TABLE IF NOT EXISTS app
(
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  secret TEXT NOT NULL UNIQUE
);